# Generated by Django 6.0.6 on 2026-07-16 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_task_options_task_order'),
        ('todo', '0003_task_owner'),
    ]

    operations = [
    ]
